create extension if not exists pgcrypto;
create extension if not exists pg_trgm;
create extension if not exists unaccent;

create table if not exists public.catalog_products (
    id uuid primary key default gen_random_uuid(),
    product_group text not null check (product_group in ('herbicide', 'fungicide', 'insecticide', 'seed_treatment')),
    source_collection text not null,
    source_product_key text not null,
    product_name text not null,
    formulation text,
    active_substances_raw text,
    manufacturer text,
    registrant text,
    producer text,
    company text,
    applicant text,
    registration_holder text,
    registration_number text,
    registration_start_date text,
    registration_end_date text,
    registration_status text,
    source_type text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source_collection, source_product_key)
);

create table if not exists public.catalog_applications (
    id bigint generated by default as identity primary key,
    product_id uuid not null references public.catalog_products(id) on delete cascade,
    source_record_id text not null,
    crop text,
    target_object text,
    rate_raw text,
    application_method text,
    waiting_period text,
    reentry_period_manual text,
    reentry_period_mech text,
    restrictions text,
    source_page text,
    source_type text,
    notes text,
    pesticide_type text,
    created_at timestamptz not null default now(),
    unique (product_id, source_record_id)
);

create index if not exists catalog_products_group_idx on public.catalog_products(product_group);
create index if not exists catalog_products_name_trgm_idx on public.catalog_products using gin (lower(product_name) gin_trgm_ops);
create index if not exists catalog_products_manufacturer_trgm_idx on public.catalog_products using gin (lower(coalesce(manufacturer, '')) gin_trgm_ops);
create index if not exists catalog_products_substances_trgm_idx on public.catalog_products using gin (lower(coalesce(active_substances_raw, '')) gin_trgm_ops);
create index if not exists catalog_applications_product_idx on public.catalog_applications(product_id);
create index if not exists catalog_applications_crop_trgm_idx on public.catalog_applications using gin (lower(coalesce(crop, '')) gin_trgm_ops);
create index if not exists catalog_applications_target_trgm_idx on public.catalog_applications using gin (lower(coalesce(target_object, '')) gin_trgm_ops);

create or replace function public.search_catalog_products(
    p_query text default '',
    p_group text default '',
    p_manufacturer text default '',
    p_culture text default '',
    p_harmful_object text default '',
    p_only_active boolean default false,
    p_limit integer default 100
)
returns table (
    product_key text,
    product_group text,
    product_name text,
    formulation text,
    active_substances_raw text,
    manufacturer text,
    registration_status text,
    applications_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
    with filtered as (
        select p.*
        from public.catalog_products p
        where
            (coalesce(trim(p_group), '') = '' or p.product_group = p_group)
            and (not p_only_active or lower(coalesce(p.registration_status, '')) = 'действует')
            and (
                coalesce(trim(p_manufacturer), '') = ''
                or lower(unaccent(coalesce(p.manufacturer, ''))) % lower(unaccent(p_manufacturer))
                or lower(unaccent(coalesce(p.manufacturer, ''))) like '%' || lower(unaccent(p_manufacturer)) || '%'
                or lower(unaccent(coalesce(p.registrant, ''))) like '%' || lower(unaccent(p_manufacturer)) || '%'
                or lower(unaccent(coalesce(p.registration_holder, ''))) like '%' || lower(unaccent(p_manufacturer)) || '%'
            )
            and (
                coalesce(trim(p_query), '') = ''
                or lower(unaccent(p.product_name)) % lower(unaccent(p_query))
                or lower(unaccent(p.product_name)) like '%' || lower(unaccent(p_query)) || '%'
                or lower(unaccent(coalesce(p.active_substances_raw, ''))) like '%' || lower(unaccent(p_query)) || '%'
                or lower(unaccent(coalesce(p.manufacturer, ''))) like '%' || lower(unaccent(p_query)) || '%'
            )
            and (
                coalesce(trim(p_culture), '') = ''
                or exists (
                    select 1 from public.catalog_applications a
                    where a.product_id = p.id
                      and lower(unaccent(coalesce(a.crop, ''))) like '%' || lower(unaccent(p_culture)) || '%'
                )
            )
            and (
                coalesce(trim(p_harmful_object), '') = ''
                or exists (
                    select 1 from public.catalog_applications a
                    where a.product_id = p.id
                      and lower(unaccent(coalesce(a.target_object, ''))) like '%' || lower(unaccent(p_harmful_object)) || '%'
                )
            )
    )
    select
        p.source_product_key,
        p.product_group,
        p.product_name,
        p.formulation,
        p.active_substances_raw,
        p.manufacturer,
        p.registration_status,
        count(a.id)::bigint
    from filtered p
    left join public.catalog_applications a on a.product_id = p.id
    group by p.id
    order by p.product_name
    limit greatest(1, least(coalesce(p_limit, 100), 500));
$$;

grant execute on function public.search_catalog_products(text, text, text, text, text, boolean, integer) to anon, authenticated, service_role;

alter table public.catalog_products enable row level security;
alter table public.catalog_applications enable row level security;

drop policy if exists "catalog products are readable" on public.catalog_products;
drop policy if exists "catalog applications are readable" on public.catalog_applications;
create policy "catalog products are readable" on public.catalog_products for select using (true);
create policy "catalog applications are readable" on public.catalog_applications for select using (true);
